### ISSUE TITLE
Remove dependencies that are of no or little use

### ISSUE THREAD

**Issue by jacksonllee** [civisanalytics/datascience-python#73]
There's probably no way to tell with certainty, but there's a good chance that some of the packages in `environment.yml` are seldom or never used in our current and foreseeable production environments, and therefore can be considered for removal to slim down the Docker image. Here's a list to start:

* beautifulsoup4
* dask
* nose
* urllib3 (requests is already included, though I don't know if production workflows depend on some crucial urllib3 features that requests doesn't support)
* dropbox
* python-simple-hipchat

Even if some of these packages are needed very occasionally, they can naturally be installed on the fly. In general, I feel like this ds-py image should only include packages that have at least medium (if not high) usage.

**Comment by stephen-hoover** [comment]
Yes, some cleanup is probably useful. I'll say that we do need `urllib3` since that's a dependency of `requests`. It might also be worth keeping `beautifulsoup4`. The datascience-python image supports ad-hoc scripts and notebooks as much as production workflows, and it's good to keep a range of tools for exploration and prototyping.

**Comment by jacksonlee-civis** [comment]
Resolved in #89
